### ISSUE TITLE
Issues compiling NovaTheSquirrel2 on Linux

### ISSUE THREAD

**Issue by undisbeliever** [NovaSquirrel/NovaTheSquirrel2#27]
I had some difficulties compiling Nova the Squirrel 2 on my Linux system and thought you should know about it.

I apologise in advance for the horrible flow, tone and length of this bug report.  I've been at it for over an hour and I haven't been able to improve it. Here goes.

<br/>

The following is preformed on the latest master branch (commit 4af1450) with the following system:

OS: ArchLinux
GNU Make Version: GNU Make 4.3
CC65 Version: ca65 V2.18
Python Version: Python 3.8.3

<br/>
<br/>

Firstly, I was unable to execute the python scripts in the tools directory.
```
> make
ca65 -g src/snesheader.s -o obj/snes/snesheader.o
ca65 -g src/init.s -o obj/snes/init.o
ca65 -g src/main.s -o obj/snes/main.o
tools/makeblocks.py
make: tools/makeblocks.py: Permission denied
make: *** [makefile:179: src/blockenum.s] Error 127
```

Changing the makefile to explicitly call `python3` fixed it for me.  While I was at it I also changed the `lz4_compress` variable as I did not have wine installed on my system. 
``` diff
diff --git a/makefile b/makefile
index d256005..0b4f1d4 100644
--- a/makefile
+++ b/makefile
@@ -40,7 +40,6 @@ imgdir2 := tilesets2
 bgdir := backgrounds
 
 lz4_flags    := -f -9
-lz4_compress := tools/lz4
 
 ifndef SNESEMU
 SNESEMU := ./mesen-s
@@ -53,8 +52,10 @@ SPCPLAY := gmeplay
 
 ifdef COMSPEC
 PY := py.exe -3 
+lz4_compress := tools/lz4
 else
-PY :=
+PY := python3
+lz4_compress := lz4
 endif
 
 # Calculate the current directory as Wine applications would see it.
```

<br/>
<br/>

Secondly, `insertthegfx.py` could not find `SPMirrorRabbit`.
```
> make
python3 tools/insertthegfx.py
Error: graphic SPMirrorRabbit does not exist
```

Renaming the `tilesets4/Sp*` files to `tilesets4/SP*` allowed me to progress further.
```
> cd tilesets4
> git mv SpMirrorRabbit.png SPMirrorRabbit.png
> git mv SpKing.png SPKing.png
```

<br/>
<br/>

Thirdly, `makeoverworldblocks.py` threw a ValueError.
```
> make
python3 tools/makeoverworldblocks.py
Traceback (most recent call last):
  File "tools/makeoverworldblocks.py", line 48, in <module>
    default_base = parseNumber(arg)
  File "/home/dev/src/snesdev/NovaTheSquirrel2/tools/nts2shared.py", line 272, in parseNumber
    return int(number)
ValueError: invalid literal for int() with base 10: 'grassy'
make: *** [makefile:185: src/overworldblockenum.s] Error 1
```

I managed to fix it with the following diff.
(I haven't looked into this deeply, maybe the scoping rules changed between the version of python you're using and the one on my system?)
``` diff
diff --git a/tools/makeoverworldblocks.py b/tools/makeoverworldblocks.py
index 7a40477..5f2103c 100644
--- a/tools/makeoverworldblocks.py
+++ b/tools/makeoverworldblocks.py
@@ -3,7 +3,6 @@
 from nts2shared import *
 
 # Globals
-aliases = {}
 default_palette = 0
 default_base = 0
 block = None
```

<br/>
<br/>

Fourthly, I ran into a few Makefile dependency issues.

Running make a second (and third) time allowed me to continue compiling.
The third dependency issue required me to manually invoke `tools/makeitems.py` to continue.
(It turns out `src/itemenum.s` was added to the git repo in commit 6c1b7973 and it's preventing make from building `src/itemdata.s`).

```
> make
...snip...
ca65 -g src/spcimage.s -o obj/snes/spcimage.o
ca65 -g src/musicseq.s -o obj/snes/musicseq.o
make: *** No rule to make target 'obj/snes/graphics.o', needed by 'auto_linker.cfg'.  Stop.
```

```
> make
...snip...
ca65 -g src/m7leveldata.s -o obj/snes/m7leveldata.o
src/m7leveldata.s(9): Error: Cannot open include file '../m7levels/sample.lz4': No such file or directory
src/m7leveldata.s(15): Error: Cannot open include file '../m7levels/sample2.lz4': No such file or directory
make: *** [makefile:135: obj/snes/m7leveldata.o] Error 1
```

```
> make
ca65 -g src/itemdata.s -o obj/snes/itemdata.o
Fatal error: Cannot open input file 'src/itemdata.s': No such file or directory
make: *** [makefile:135: obj/snes/itemdata.o] Error 1
```

```
> make src/itemdata.s
make: Nothing to be done for 'src/itemdata.s'.
```

```
> make -B src/itemenum.s
python3 tools/makeitems.py
```

```
> make
ca65 -g src/blockinteraction.s -o obj/snes/blockinteraction.o
ca65 -g src/itemcode.s -o obj/snes/itemcode.o
ca65 -g src/itemdata.s -o obj/snes/itemdata.o
...snip...
```

<br/>
<br/>

Finally, I came across two unresolved symbol errors.

```
> make
ld65 -o nova-the-squirrel-2.sfc -m map.txt --dbgfile nova-the-squirrel-2.dbg -C auto_linker.cfg obj/snes/snesheader.o obj/snes/init.o obj/snes/main.o obj/snes/player.o obj/snes/memory.o obj/snes/common.o obj/snes/renderlevel.o obj/snes/renderlevel2.o obj/snes/uploadppu.o obj/snes/blarggapu.o obj/snes/spcimage.o obj/snes/musicseq.o obj/snes/graphics.o obj/snes/blockdata.o obj/snes/scrolling.o obj/snes/playergraphics.o obj/snes/blockinteraction.o obj/snes/palettedata.o obj/snes/levelload.o obj/snes/levelautotile.o obj/snes/leveldata.o obj/snes/actordata.o obj/snes/actorcode.o obj/snes/object.o obj/snes/mode7.o obj/snes/perspective_data.o obj/snes/sincos_data.o obj/snes/huffmunch.o obj/snes/inventory.o obj/snes/vwf.o obj/snes/overworldblockdata.o obj/snes/overworlddata.o obj/snes/overworldcode.o obj/snes/m7leveldata.o obj/snes/math.o obj/snes/portraitdata.o obj/snes/dialog.o obj/snes/namefont.o obj/snes/namefontwidth.o obj/snes/vwf_fontdata.o obj/snes/lz4.o obj/snes/dialog_npc_data.o obj/snes/dialog_text_data.o obj/snes/itemcode.o obj/snes/itemdata.o obj/snes/backgrounddata.o obj/snes/bgeffectcode.o obj/snes/playerdraw.o obj/snes/playerability.o
Unresolved external 'DialogScene_NovaMaffiTest2' referenced in:
  src/leveldata.s(156)
  src/leveldata.s(156)
  src/leveldata.s(156)
Unresolved external 'DialogScene_NovaWhatIsSlope' referenced in:
  src/leveldata.s(263)
  src/leveldata.s(263)
  src/leveldata.s(263)
ld65: Error: 2 unresolved external(s) found - cannot create output file
make: *** [makefile:128: nova-the-squirrel-2.sfc] Error 1
```

As I could not find these two Dialog symbols in the code I just added them to the `dialog.txt` file.
``` diff
diff --git a/story/dialog.txt b/story/dialog.txt
index 5c93b9c..c01ef70 100644
--- a/story/dialog.txt
+++ b/story/dialog.txt
@@ -44,3 +44,12 @@ another!
 Hi I'm a taur!
 {-}
 {End}
+
+
+--- NovaMaffiTest2
+{End}
+
+
+--- NovaWhatIsSlope
+{End}
+
```

<br/>

And I was finally able to compile `nova-the-squirrel-2.sfc`.

Thank-you for having the patience to read through this bug report.

 -- UnDisbeliever

P.S. I tried out `nova-the-squirrel-2.sfc` and liked what I experienced. Keep up the good work.

**Comment by NovaSquirrel** [comment]
Aside from case-sensitivity most of this is a result of changes I didn't commit yet, or a Python refactor I did but evidently didn't actually test. I'll get all of that taken care of, and fix the dependency issues.

**Comment by undisbeliever** [comment]
I figured that was the case.

Latest master (5c59edd) now compiles after executing make twice.

---

It took a while, but I discovered why make tries to link `nova-the-squirrel-2.sfc` before assembling `obj/snes/graphics.o`.

The fault lies in this makefile rule:
``` makefile
$(objdir)/graphics.o: $(srcdir)/graphicsenum.s
```

When `src/graphics.s` does not exist, make believes `obj/snes/graphics.o` has a single dependency (`src/graphicsenum.s`) and can be built without executing a command.

```
> rm src/graphics.s obj/snes/graphics.o
> make --debug=all --just-print obj/snes/graphics.o
...snip...
  No need to remake target 'src/graphicsenum.s'.
 Finished prerequisites of target file 'obj/snes/graphics.o'.
Must remake target 'obj/snes/graphics.o'.
Successfully remade target file 'obj/snes/graphics.o'.
make: Nothing to be done for 'obj/snes/graphics.o'.
```

When `src/graphics.s` does exist, the `$(objdir)/%.o: $(srcdir)/%.s` rule kicks in and `graphics.o` can be assembled correctly.

The following patch fixes the issue.
``` diff
diff --git a/makefile b/makefile
index 2117ad7..e302755 100644
--- a/makefile
+++ b/makefile
@@ -144,7 +144,8 @@ $(objdir)/mktables.s: tools/mktables.py
 $(objdir)/spcimage.o: $(brrlisto)
 
 # Files that depend on enums
-$(objdir)/graphics.o: $(srcdir)/graphicsenum.s
+$(srcdir)/graphics.s: $(srcdir)/graphicsenum.s
 $(objdir)/blockdata.o: $(srcdir)/blockenum.s
 $(objdir)/overworldblockdata.o: $(srcdir)/overworldblockenum.s
 $(objdir)/player.o: $(srcdir)/blockenum.s $(srcdir)/actorenum.s $(srcdir)/blockenum.s
```


<br/>
<br/>


I also needed to make the following changes to the makefile for make to compile `nova-the-squirrel-2.sfc` in a single run of `make -j888` on a clean repo (on my system).

``` diff
diff --git a/makefile b/makefile
index 2117ad7..96c67d4 100644
--- a/makefile
+++ b/makefile
@@ -144,7 +144,10 @@ $(objdir)/mktables.s: tools/mktables.py
 $(objdir)/spcimage.o: $(brrlisto)
 
 # Files that depend on enums
-$(objdir)/graphics.o: $(srcdir)/graphicsenum.s
+$(srcdir)/graphics.s: $(srcdir)/graphicsenum.s
+$(srcdir)/backgrounddata.s: $(srcdir)/backgroundenum.s $(srcdir)/graphicsenum.s
+$(srcdir)/portraitdata.s: $(srcdir)/portraitenum.s
+
 $(objdir)/blockdata.o: $(srcdir)/blockenum.s
 $(objdir)/overworldblockdata.o: $(srcdir)/overworldblockenum.s
 $(objdir)/player.o: $(srcdir)/blockenum.s $(srcdir)/actorenum.s $(srcdir)/blockenum.s
@@ -165,7 +168,7 @@ $(objdir)/itemcode.o: $(srcdir)/itemenum.s
 $(objdir)/dialog.o: $(srcdir)/vwf.inc $(srcdir)/paletteenum.s $(srcdir)/graphicsenum.s
 $(objdir)/vwf.o: $(srcdir)/vwf.inc
 $(objdir)/namefont.o: tilesets2/DialogNameFont.chrgb $(srcdir)/namefontwidth.s
-$(objdir)/dialog_text_data.s.o: $(srcdir)/paletteenum.s $(srcdir)/graphicsenum.s $(srcdir)/dialog_npc_enum.s $(srcdir)/vwf.inc $(srcdir)/blockenum.s $(srcdir)/portraitenum.s
+$(objdir)/dialog_text_data.o: $(srcdir)/paletteenum.s $(srcdir)/graphicsenum.s $(srcdir)/dialog_npc_enum.s $(srcdir)/vwf.inc $(srcdir)/blockenum.s $(srcdir)/portraitenum.s
 $(srcdir)/namefontwidth.s: tilesets2/DialogNameFont.chrgb
 	$(PY) tools/namefontwidthtable.py
 $(srcdir)/vwf_fontdata.s: tools/fonts/BaseSeven.png tools/makefontvwf.py
```


<br/>
<br/>


P.S. While I was debugging the makefile I found some undefined variables.
```
`--> make --just-print --warn-undefined-variables
makefile:189: warning: undefined variable 'portraits'
makefile:190: warning: undefined variable 'portraits'
makefile:194: warning: undefined variable 'portraits'
makefile:254: warning: undefined variable 'm7levels'
```

**Comment by NovaSquirrel** [comment]
That works, thanks for your help! Looks like the `portaits` typo struck once again

**Comment by undisbeliever** [comment]
Looking into the matter further I discovered a proper fix for the multiple targets dependency issues - grouped explicit targets (https://stackoverflow.com/a/59877127).

Unfortunately it requires GNU make version 4.3 (latest version, released 19 Jan 2020). It might not be worth implementing just yet, but I figured you should know about it.

The following diff only updates the rules for backgrounds, graphics and portraits, but it is a simple manner to extend it to the rest of the code generating scripts.

It compiles `nova-the-squirrel-2.sfc` with `make -j888` on a clean repo, only executing the `insertthegfx.py`, `makebackgrounds.py`, and `encodeportraits.py` scripts once.

It also handles the case where `src/portraitdata.s` is missing but `src/portraitenum.s` exists.

Diff against commit c21c820
``` diff
diff --git a/makefile b/makefile
index 5c4f1b9..267c588 100644
--- a/makefile
+++ b/makefile
@@ -144,9 +144,9 @@ $(objdir)/mktables.s: tools/mktables.py
 $(objdir)/spcimage.o: $(brrlisto)
 
 # Files that depend on enums
-$(srcdir)/graphics.s: $(srcdir)/graphicsenum.s
-$(srcdir)/backgrounddata.s: $(srcdir)/backgroundenum.s $(srcdir)/graphicsenum.s
-$(srcdir)/portraitdata.s: $(srcdir)/portraitenum.s
+$(objdir)/graphics.o: $(srcdir)/graphicsenum.s
+$(objdir)/backgrounddata.o: $(srcdir)/backgroundenum.s $(srcdir)/graphicsenum.s
+$(objdir)/portraitdata.o: $(srcdir)/portraitenum.s
 
 $(objdir)/blockdata.o: $(srcdir)/blockenum.s
 $(objdir)/overworldblockdata.o: $(srcdir)/overworldblockenum.s
@@ -175,7 +175,7 @@ $(srcdir)/vwf_fontdata.s: tools/fonts/BaseSeven.png tools/makefontvwf.py
 	$(PY) tools/makefontvwf.py
 
 # Automatically insert graphics into the ROM
-$(srcdir)/graphicsenum.s: $(chr2all) $(chr4all) $(chr4allbackground) $(chr4_lz4) $(chr2_lz4) tools/gfxlist.txt tools/insertthegfx.py
+$(srcdir)/graphics.s $(srcdir)/graphicsenum.s &: $(chr2all) $(chr4all) $(chr4allbackground) $(chr4_lz4) $(chr2_lz4) tools/gfxlist.txt tools/insertthegfx.py
 	$(PY) tools/insertthegfx.py
 
 # Automatically create the list of blocks from a description
@@ -189,10 +189,9 @@ $(srcdir)/overworldblockenum.s: tools/overworldblocks.txt
 	$(PY) tools/makeoverworldblocks.py
 
 
-
-$(objdir)/portraitdata.o: $(portraits) $(srcdir)/portraitenum.s
-$(srcdir)/portraitenum.s: $(portraits) tools/encodeportraits.py
+$(srcdir)/portraitenum.s $(srcdir)/portraitdata.s &: $(portraits) tools/encodeportraits.py
 	$(PY) tools/encodeportraits.py
+
 $(objdir)/dialog.o: $(srcdir)/dialog_npc_enum.s
 $(srcdir)/dialog_npc_data.s: $(srcdir)/dialog_npc_enum.s
 $(srcdir)/dialog_npc_enum.s: $(portraits) $(all_npc_gfx) tools/makenpc.py
@@ -204,8 +203,10 @@ $(srcdir)/actorenum.s: tools/actors.txt tools/makeactor.py
 	$(PY) tools/makeactor.py
 $(srcdir)/itemenum.s: tools/items.txt tools/makeitems.py
 	$(PY) tools/makeitems.py
-$(srcdir)/backgroundenum.s: tools/backgrounds.txt tools/makebackgrounds.py
+
+$(srcdir)/backgroundenum.s $(srcdir)/backgrounddata.s &: tools/backgrounds.txt tools/makebackgrounds.py
 	$(PY) tools/makebackgrounds.py
+
 $(srcdir)/leveldata.s: $(levels) tools/levelconvert.py
 	$(PY) tools/levelconvert.py
 $(srcdir)/overworlddata.s: $(overworlds) tools/overworld.py
@@ -224,7 +225,6 @@ m7levels/%.bin: m7levels/%.tmx tools/m7levelconvert.py
 $(srcdir)/m7leveldata.s: $(m7levels_lz4) $(m7levels_bin) tools/m7levelinsert.py
 	$(PY) tools/m7levelinsert.py
 $(objdir)/m7leveldata.o: $(m7levels_lz4) $(m7levels_bin) $(srcdir)/m7leveldata.s
-$(objdir)/backgrounddata.o: $(srcdir)/backgroundenum.s

```
